// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVmnRPVuPu7CjNKtJD3XvNiThLeI4NCI',
    appId: '1:849798385006:web:d029d6fea453055150457f',
    messagingSenderId: '849798385006',
    projectId: 'cross-puzzle-d3c56',
    authDomain: 'cross-puzzle-d3c56.firebaseapp.com',
    storageBucket: 'cross-puzzle-d3c56.firebasestorage.app',
    measurementId: 'G-NZ17TYDR05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJ5T5VL16C_fiQ9IAP4onbeqnQllPUQ8',
    appId: '1:849798385006:android:0ea222f040a8790250457f',
    messagingSenderId: '849798385006',
    projectId: 'cross-puzzle-d3c56',
    storageBucket: 'cross-puzzle-d3c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1l1K4a0ZUsb-oVMhZ-ocnxrfU2Mn-mI',
    appId: '1:849798385006:ios:ad1aa07c2b76314c50457f',
    messagingSenderId: '849798385006',
    projectId: 'cross-puzzle-d3c56',
    storageBucket: 'cross-puzzle-d3c56.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1l1K4a0ZUsb-oVMhZ-ocnxrfU2Mn-mI',
    appId: '1:849798385006:ios:ad1aa07c2b76314c50457f',
    messagingSenderId: '849798385006',
    projectId: 'cross-puzzle-d3c56',
    storageBucket: 'cross-puzzle-d3c56.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLVmnRPVuPu7CjNKtJD3XvNiThLeI4NCI',
    appId: '1:849798385006:web:2f059d1dc24b64a350457f',
    messagingSenderId: '849798385006',
    projectId: 'cross-puzzle-d3c56',
    authDomain: 'cross-puzzle-d3c56.firebaseapp.com',
    storageBucket: 'cross-puzzle-d3c56.firebasestorage.app',
    measurementId: 'G-9BTLSZS9DC',
  );
}
